
version: '2'

services:
  pg-slave:
    build: '.'
    # image: 'danieldent/postgres-replication'
    restart: 'always'
    environment:
      PGPORT: '5433'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      PGDATA: '/var/lib/postgresql/data/pgdata'
      REPLICATE_FROM: '192.168.1.187'
    volumes:
     - '/var/lib/postgresql/data'
    # expose:
    #  - '5432'
    # ports:
    #   - "5433:5432"
    network_mode: "host"
    # networks:
    #   host: {}
    #   # hostnet: {}
    # external_links:
    #  - 'pg-master'

# networks:
#   hostnet:
#     external:
#       name: formaster_mynet1
