
version: '2'

services:
  pg-slave:
    build: '.'
    # image: 'danieldent/postgres-replication'
    restart: 'always'
    environment:
      # PGPORT: '5433'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      PGDATA: '/var/lib/postgresql/data/pgdata'
      REPLICATE_FROM: '192.168.1.55'
    volumes:
     - '/var/lib/postgresql/data'
    # expose:
    #  - '5432'
<<<<<<< HEAD
    ports:
=======
    # ports:
>>>>>>> 643b96269105c41e521e466538ec9a5b7d1e928d
      - "5432:5432"
    network_mode: "host"
    # networks:
    #   host: {}
    #   # hostnet: {}
    # external_links:
    #  - 'pg-master'

# networks:
#   hostnet:
#     external:
#       name: formaster_mynet1
