
version: '2'

services:
  pg-master:
    build: '.'
    # image: 'danieldent/postgres-replication'
    restart: 'always'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
     - '/var/lib/postgresql/data'
    network_mode: "host"
    ports:
      - "5432:5432"
    # networks:
    #   host: {}
      # mynet1: {}

# networks:
#   mynet1:
#     driver: bridge
